### ISSUE TITLE
Using the command key in TMUX

### ISSUE THREAD

**Issue by joelgrimberg** [dmtrKovalenko/my-nvim-config#1]
I am wondering if you use neovim within TMUX.
It looks like TMUX does not recognize the ⌘ key (<D - .. >)

**Comment by dmtrKovalenko** [comment]
Cool to see interest to my config!

I do not use tmux and instead uxing neovim as tmux managing command line sessions with editor and even just command line sessions for scenarios when a lot of process must run in parallel

<img width="1684" alt="image" src="https://github.com/user-attachments/assets/c7435693-5d05-4d6a-84bf-73c7ed74458f">

**Comment by joelgrimberg** [comment]
Ah. Well, if you ever would make a short YouTube on how you work with that, I would most def. take a look! :D
